package LibraryInterface;

/**
* LibraryInterface/IDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from library.idl
* Friday, March 1, 2019 6:38:28 PM EST
*/

public final class IDHolder implements org.omg.CORBA.portable.Streamable
{
  public LibraryInterface.ID value = null;

  public IDHolder ()
  {
  }

  public IDHolder (LibraryInterface.ID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LibraryInterface.IDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LibraryInterface.IDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LibraryInterface.IDHelper.type ();
  }

}
