package LibraryInterface;


/**
* LibraryInterface/ItemIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from library.idl
* Friday, March 1, 2019 6:38:28 PM EST
*/

public final class ItemIDHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ItemIDHolder ()
  {
  }

  public ItemIDHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LibraryInterface.ItemIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LibraryInterface.ItemIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LibraryInterface.ItemIDHelper.type ();
  }

}
