package LibraryInterface;


/**
* LibraryInterface/ItemNameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from library.idl
* Friday, March 1, 2019 6:38:28 PM EST
*/

public final class ItemNameHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ItemNameHolder ()
  {
  }

  public ItemNameHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LibraryInterface.ItemNameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LibraryInterface.ItemNameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LibraryInterface.ItemNameHelper.type ();
  }

}
