package LibraryInterface;


/**
* LibraryInterface/LibraryServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from library.idl
* Friday, March 1, 2019 6:38:28 PM EST
*/

public interface LibraryServer extends LibraryServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LibraryServer
