package LibraryInterface;


/**
* LibraryInterface/LibraryServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from library.idl
* Friday, March 1, 2019 6:38:28 PM EST
*/

public interface LibraryServerOperations 
{
  String addItem (LibraryInterface.ID managerID, LibraryInterface.ID itemID, String itemName, int quantity);
  String deleteItem (LibraryInterface.ID managerID, LibraryInterface.ID itemID, int quantity);
  String listItemAvailability (LibraryInterface.ID managerID);
  String borrowItem (LibraryInterface.ID userID, LibraryInterface.ID itemID, int numberOfDay);
  String findItem (LibraryInterface.ID userID, String itemName, boolean recursive);
  String returnItem (LibraryInterface.ID userID, LibraryInterface.ID itemID);
  String exchangeItem (LibraryInterface.ID userID, LibraryInterface.ID oldItemID, LibraryInterface.ID newItemID);
  String addWaitList (LibraryInterface.ID userID, LibraryInterface.ID itemID);
} // interface LibraryServerOperations
