package LibraryInterface;

/**
* LibraryInterface/LibraryServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from library.idl
* Friday, March 1, 2019 6:38:28 PM EST
*/

public final class LibraryServerHolder implements org.omg.CORBA.portable.Streamable
{
  public LibraryInterface.LibraryServer value = null;

  public LibraryServerHolder ()
  {
  }

  public LibraryServerHolder (LibraryInterface.LibraryServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LibraryInterface.LibraryServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LibraryInterface.LibraryServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LibraryInterface.LibraryServerHelper.type ();
  }

}
