package LibraryInterface;


/**
* LibraryInterface/LibraryServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from library.idl
* Friday, March 1, 2019 6:38:28 PM EST
*/

abstract public class LibraryServerHelper
{
  private static String  _id = "IDL:LibraryInterface/LibraryServer:1.0";

  public static void insert (org.omg.CORBA.Any a, LibraryInterface.LibraryServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LibraryInterface.LibraryServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LibraryInterface.LibraryServerHelper.id (), "LibraryServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LibraryInterface.LibraryServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LibraryServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LibraryInterface.LibraryServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LibraryInterface.LibraryServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LibraryInterface.LibraryServer)
      return (LibraryInterface.LibraryServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LibraryInterface._LibraryServerStub stub = new LibraryInterface._LibraryServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LibraryInterface.LibraryServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LibraryInterface.LibraryServer)
      return (LibraryInterface.LibraryServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LibraryInterface._LibraryServerStub stub = new LibraryInterface._LibraryServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
