package LibraryInterface;


/**
* LibraryInterface/LibraryServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from library.idl
* Friday, March 1, 2019 6:38:28 PM EST
*/

public abstract class LibraryServerPOA extends org.omg.PortableServer.Servant
 implements LibraryInterface.LibraryServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addItem", new java.lang.Integer (0));
    _methods.put ("deleteItem", new java.lang.Integer (1));
    _methods.put ("listItemAvailability", new java.lang.Integer (2));
    _methods.put ("borrowItem", new java.lang.Integer (3));
    _methods.put ("findItem", new java.lang.Integer (4));
    _methods.put ("returnItem", new java.lang.Integer (5));
    _methods.put ("exchangeItem", new java.lang.Integer (6));
    _methods.put ("addWaitList", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // LibraryInterface/LibraryServer/addItem
       {
         LibraryInterface.ID managerID = LibraryInterface.IDHelper.read (in);
         LibraryInterface.ID itemID = LibraryInterface.IDHelper.read (in);
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.addItem (managerID, itemID, itemName, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // LibraryInterface/LibraryServer/deleteItem
       {
         LibraryInterface.ID managerID = LibraryInterface.IDHelper.read (in);
         LibraryInterface.ID itemID = LibraryInterface.IDHelper.read (in);
         int quantity = in.read_long ();
         String $result = null;
         $result = this.deleteItem (managerID, itemID, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // LibraryInterface/LibraryServer/listItemAvailability
       {
         LibraryInterface.ID managerID = LibraryInterface.IDHelper.read (in);
         String $result = null;
         $result = this.listItemAvailability (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // LibraryInterface/LibraryServer/borrowItem
       {
         LibraryInterface.ID userID = LibraryInterface.IDHelper.read (in);
         LibraryInterface.ID itemID = LibraryInterface.IDHelper.read (in);
         int numberOfDay = in.read_long ();
         String $result = null;
         $result = this.borrowItem (userID, itemID, numberOfDay);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // LibraryInterface/LibraryServer/findItem
       {
         LibraryInterface.ID userID = LibraryInterface.IDHelper.read (in);
         String itemName = in.read_string ();
         boolean recursive = in.read_boolean ();
         String $result = null;
         $result = this.findItem (userID, itemName, recursive);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // LibraryInterface/LibraryServer/returnItem
       {
         LibraryInterface.ID userID = LibraryInterface.IDHelper.read (in);
         LibraryInterface.ID itemID = LibraryInterface.IDHelper.read (in);
         String $result = null;
         $result = this.returnItem (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // LibraryInterface/LibraryServer/exchangeItem
       {
         LibraryInterface.ID userID = LibraryInterface.IDHelper.read (in);
         LibraryInterface.ID oldItemID = LibraryInterface.IDHelper.read (in);
         LibraryInterface.ID newItemID = LibraryInterface.IDHelper.read (in);
         String $result = null;
         $result = this.exchangeItem (userID, oldItemID, newItemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // LibraryInterface/LibraryServer/addWaitList
       {
         LibraryInterface.ID userID = LibraryInterface.IDHelper.read (in);
         LibraryInterface.ID itemID = LibraryInterface.IDHelper.read (in);
         String $result = null;
         $result = this.addWaitList (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LibraryInterface/LibraryServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LibraryServer _this() 
  {
    return LibraryServerHelper.narrow(
    super._this_object());
  }

  public LibraryServer _this(org.omg.CORBA.ORB orb) 
  {
    return LibraryServerHelper.narrow(
    super._this_object(orb));
  }


} // class LibraryServerPOA
