package LibraryInterface;


/**
* LibraryInterface/QuantityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from library.idl
* Friday, March 1, 2019 6:38:28 PM EST
*/

public final class QuantityHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public QuantityHolder ()
  {
  }

  public QuantityHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LibraryInterface.QuantityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LibraryInterface.QuantityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LibraryInterface.QuantityHelper.type ();
  }

}
